version: "3.3"
    
services:
  db:
    # container_name : mariadb
    build : ./requirements/mariadb/
    restart: unless-stopped
    privileged: true
    # volumes:
      #  - /home/hmellahi/data/db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - mariab-db-net
    container_name: "db"
  wordpress:
    env_file:
      - .env
    # restart: always
    depends_on: 
      - db
    build : ./requirements/wordpress/
    ports:
      - "9000:9000"
    volumes:
      - type: bind
        source: /home/hmellahi/data/wordpress
        target: /var/www/wordpress
    networks:
      - php-net
      - mariab-db-net
    container_name: "wordpress"
  nginx:
    build : ./requirements/nginx/
    # restart: always
    depends_on: 
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    networks:
      - php-net
    container_name: "nginx"
    volumes:
      - type: bind
        source: /home/hmellahi/data/wordpress
        target: /var/www/wordpress
    # volumes:
    #   - type: bind
    #     source: /home/hmellahi/data/phpmyadmin
    #     target: /var/www/phpmyadmin
  # adminer:
  #   build : ./requirements/adminer/
  #   networks:
  #     - custom-net
    # volumes:
      # - /home/hmellahi/data/adminer:/usr/share/adminer/
  phpmyadmin:
    # volumes:
    #   - type: bind
    #     source: /home/hmellahi/data/phpmyadmin
    #     target: /usr/share/phpmyadmin
    build : ./requirements/phpmyadmin/
    networks:
      - mariab-db-net
    container_name: "phpmyadmin"
networks:   
  php-net:
  mariab-db-net:
  # data:
  # "/home/hmellahi/data/phpmyadmin"