version: "3"
    
services:
  db:
    build : ./requirements/mariadb/
    restart: always
    privileged: true
    volumes:
       - mariadb:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - mariab-db-net
    container_name: "db"
  wordpress:
    env_file:
      - .env
    restart: always
    depends_on: 
      - db
    build : ./requirements/wordpress/
    volumes:
       - wordpress:/var/www/wordpress
       - phpmyadmin:/var/www/phpmyadmin
       - adminer:/var/www/adminer
    networks:
      - php-net
      - mariab-db-net
    container_name: "wordpress"
  nginx:
    build : ./requirements/nginx/
    restart: always
    depends_on: 
      - wordpress
    ports:
      - "443:443"
    networks:
      - php-net
    container_name: "nginx"
    volumes:
      - wordpress:/var/www/wordpress
      - phpmyadmin:/var/www/phpmyadmin
      - adminer:/var/www/adminer
    env_file:
      - .env
  adminer:
    build : ./requirements/adminer/
    restart: on-failure
    networks:
      - mariab-db-net
    volumes:
      - adminer:/usr/share/adminer/adminer/
    container_name: "adminer"
  phpmyadmin:
    build : ./requirements/phpmyadmin/
    restart: on-failure
    volumes:
      - phpmyadmin:/usr/share/phpmyadmin
    networks:
      - mariab-db-net
    container_name: "phpmyadmin"
networks:   
  php-net:
  mariab-db-net:

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hmellahi/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hmellahi/data/wordpress'
  phpmyadmin:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hmellahi/data/phpmyadmin'
  adminer:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hmellahi/data/adminer'
