version: "3"
    
services:
  db:
    build : ./requirements/mariadb/
    restart: on-failure
    privileged: true
    volumes:
       - mariadb:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - mariab-db-net
    container_name: "db"
  wordpress:
    env_file:
      - .env
    restart: on-failure
    depends_on: 
      - db
    build : ./requirements/wordpress/
    volumes:
       - wordpress:/var/www/wordpress
       - phpmyadmin:/var/www/phpmyadmin
    networks:
      - php-net
      - mariab-db-net
    container_name: "wordpress"
  nginx:
    build : ./requirements/nginx/
    restart: on-failure
    depends_on: 
      - wordpress
    ports:
      - "443:443"
    networks:
      - php-net
    container_name: "nginx"
    volumes:
      - wordpress:/var/www/wordpress
      - phpmyadmin:/var/www/phpmyadmin
    env_file:
      - .env
  # adminer:
  #   build : ./requirements/adminer/
  #   restart: on-failure
  #   networks:
  #     - mariab-db-net
  #   volumes:
  #     - /home/hmellahi/data/adminer:/usr/share/adminer/
  #   container_name: "adminer"
  phpmyadmin:
    build : ./requirements/phpmyadmin/
    restart: on-failure
    volumes:
      - phpmyadmin:/usr/share/phpmyadmin
    networks:
      - mariab-db-net
    container_name: "phpmyadmin"
networks:   
  php-net:
  mariab-db-net:

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/lib/boot2docker/home/hmellahi/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/lib/boot2docker/home/hmellahi/data/wordpress'
  phpmyadmin:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/lib/boot2docker/home/hmellahi/data/phpmyadmin'