version: "3.3"
    
services:
  db:
    build : ./requirements/mariadb/
    restart: unless-stopped
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - /home/hamza/data/db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - custom-net
  wordpress:
    env_file:
      - .env
    restart: always
    depends_on: 
      - db
    build : ./requirements/wordpress/
    ports:
      - "9000:9000"
      # - "8000:80"
    volumes:
      # - ./test:/var/www/test
      - /home/hamza/data/wordpress:/var/www/wordpress
    networks:
      - custom-net
  nginx:
    build : ./requirements/nginx/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - custom-net
    links:
      - wordpress
      - db
    volumes:
      # - data:etc/nginx/sites-available/default
      - /home/hamza/data/wordpress:/var/www/wordpress
networks: 
  custom-net:
# volumes: 
  # data:
    # requirements/nginx/default