version: "3"
    
services:
  mariadb:
    build : ./requirements/mariadb/
    restart: always
    privileged: true
    volumes:
       - mariadb:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - mariab-db-net
    container_name: "mariadb"
    image : "mariadb"
    
  wordpress:
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
    build : ./requirements/wordpress/
    volumes:
       - wordpress:/var/www/wordpress
       - phpmyadmin:/var/www/wordpress/phpmyadmin
       - adminer:/var/www/wordpress/adminer
    networks:
      - php-net
      - mariab-db-net
    container_name: "wordpress"
    image : "wordpress"

  nginx:
    build : ./requirements/nginx/
    restart: always
    depends_on: 
      - wordpress
    ports:
      - "443:443"
    networks:
      - php-net
    container_name: "nginx"
    image : "nginx"
    volumes:
      - wordpress:/var/www/wordpress
      - phpmyadmin:/var/www/wordpress/phpmyadmin
      - adminer:/var/www/wordpress/adminer
    env_file:
      - .env

  adminer:
    build : ./requirements/bonus/adminer/
    restart: on-failure
    networks:
      - mariab-db-net
    volumes:
      - adminer:/usr/share/adminer/adminer/
    container_name: "adminer"
    image : "adminer"
  
  phpmyadmin:
    build : ./requirements/bonus/phpmyadmin/
    restart: on-failure
    volumes:
      - phpmyadmin:/usr/share/phpmyadmin
    networks:
      - mariab-db-net
    container_name: "phpmyadmin"
    image : "phpmyadmin"

networks:   
  php-net:
  mariab-db-net:

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hmellahi/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hmellahi/data/wordpress'
  phpmyadmin:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hmellahi/data/phpmyadmin'
  adminer:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hmellahi/data/adminer'
