version: "3.3"
    
services:
  db:
    build : ./requirements/mariadb/
    restart: on-failure
    privileged: true
    # volumes:
    #    - /var/lib/boot2docker/home/hmellahi/data/mariab:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - mariab-db-net
    container_name: "db"
  wordpress:
    env_file:
      - .env
    restart: on-failure
    depends_on: 
      - db
    build : ./requirements/wordpress/
    volumes:
       - /var/lib/boot2docker/home/hmellahi/data/wordpress:/var/www/wordpress
    networks:
      - php-net
      - mariab-db-net
    container_name: "wordpress"
  nginx:
    build : ./requirements/nginx/
    restart: on-failure
    depends_on: 
      - wordpress
    ports:
      - "443:443"
    networks:
      - php-net
    container_name: "nginx"
    volumes:
      - /var/lib/boot2docker/home/hmellahi/data/wordpress:/var/www/wordpress
      - /var/lib/boot2docker/home/hmellahi/data/phpmyadmin:/var/www/phpmyadmin
    env_file:
      - .env
  # adminer:
  #   build : ./requirements/adminer/
  #   restart: on-failure
  #   networks:
  #     - mariab-db-net
  #   volumes:
  #     - /home/hmellahi/data/adminer:/usr/share/adminer/
  #   container_name: "adminer"
  phpmyadmin:
    build : ./requirements/phpmyadmin/
    restart: on-failure
    volumes:
      - /var/lib/boot2docker/home/hmellahi/data/phpmyadmin:/usr/share/phpmyadmin
    networks:
      - mariab-db-net
    container_name: "phpmyadmin"
networks:   
  php-net:
  mariab-db-net:
volumes:
  gogs-data: